port=0
log-dhcp
interface=__PXE_INTERFACE__
bind-interfaces
dhcp-range=__PXE_SUBNET__,proxy,__PXE_NETMASK__
dhcp-no-override
dhcp-userclass=set:ipxe,iPXE
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:ipxe,__PROXY_HTTP_URL__/boot/menu.ipxe
dhcp-boot=tag:efi-x86_64,__PXE_BOOTFILE_UEFI__,,__PXE_NEXT_SERVER__
dhcp-boot=tag:!ipxe,tag:!efi-x86_64,__PXE_BOOTFILE_BIOS__,,__PXE_NEXT_SERVER__
