port=0
log-dhcp
interface=__PXE_INTERFACE__
bind-interfaces
domain=__PXE_DOMAIN__
dhcp-range=__PXE_DHCP_RANGE_START__,__PXE_DHCP_RANGE_END__,12h
dhcp-option=option:router,__PXE_GATEWAY__
dhcp-option=option:dns-server,__PXE_DNS_SERVERS__
dhcp-userclass=set:ipxe,iPXE
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:ipxe,__PROXY_HTTP_URL__/boot/menu.ipxe
dhcp-boot=tag:efi-x86_64,__PXE_BOOTFILE_UEFI__,,__PXE_NEXT_SERVER__
dhcp-boot=tag:!ipxe,tag:!efi-x86_64,__PXE_BOOTFILE_BIOS__,,__PXE_NEXT_SERVER__
dhcp-no-override
